version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://python-backend:5000
    depends_on:
      - python-backend

  python-backend:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./python-backend:/app
